// Generated by CoffeeScript 1.4.0

module.exports = (function() {
  var Timer, alias, timer, validate;
  alias = function(klass, names, action) {
    var name, _i, _len, _results;
    names = names.split(',');
    _results = [];
    for (_i = 0, _len = names.length; _i < _len; _i++) {
      name = names[_i];
      _results.push(klass.prototype[name] = action);
    }
    return _results;
  };
  validate = function(timeout, action) {
    var _ref;
    if (typeof action === 'number') {
      _ref = [timeout, action], action = _ref[0], timeout = _ref[1];
    }
    if (!isFinite(timeout)) {
      throw new Error('timeout is not a valid number');
    }
    if (typeof action !== 'function') {
      throw new Error('action is not a function');
    }
    return [timeout, action];
  };
  Timer = (function() {

    function Timer() {}

    return Timer;

  })();
  alias(Timer, 'n,nt,tick,nexttick,nextTick', function(action) {
    if (typeof action !== 'function') {
      throw new Error('action is not a function');
    }
    if (process && process.nextTick) {
      return process.nextTick(action);
    } else {
      return setTimeout(action, 0);
    }
  });
  alias(Timer, 't,to,timeout,setTimeout', function(timeout, action) {
    var _ref;
    _ref = validate(timeout, action), timeout = _ref[0], action = _ref[1];
    return setTimeout(action, timeout);
  });
  alias(Timer, 'c,ct,cto,clear,clearTimeout', function(handle) {
    return clearTimeout(handle);
  });
  alias(Timer, 'i,in,iv,interval,setInterval', function(timeout, action) {
    var _ref;
    _ref = validate(timeout, action), timeout = _ref[0], action = _ref[1];
    return setInterval(action, timeout);
  });
  timer = new Timer();
  Timer.prototype.Timer = Timer;
  return timer;
})();
