// Generated by CoffeeScript 1.4.0
var __slice = [].slice;

module.exports = (function() {
  var Timer, alias, timer, validate;
  alias = function() {
    var action, klass, name, names, _i, _j, _len, _results;
    klass = arguments[0], names = 3 <= arguments.length ? __slice.call(arguments, 1, _i = arguments.length - 1) : (_i = 1, []), action = arguments[_i++];
    _results = [];
    for (_j = 0, _len = names.length; _j < _len; _j++) {
      name = names[_j];
      _results.push(klass.prototype[name] = action);
    }
    return _results;
  };
  validate = function(timeout, action) {
    var _ref;
    if (typeof action === 'number') {
      _ref = [timeout, action], action = _ref[0], timeout = _ref[1];
    }
    if (!isFinite(timeout)) {
      throw new Error('timeout is not a valid number');
    }
    if (typeof action !== 'function') {
      throw new Error('action is not a function');
    }
    return [timeout, action];
  };
  Timer = (function() {

    function Timer() {}

    return Timer;

  })();
  alias.apply(null, [Timer].concat(__slice.call('t,to,timeout,setTimeout'.split(',')), [function(timeout, action) {
    var _ref;
    _ref = validate(timeout, action), timeout = _ref[0], action = _ref[1];
    return setTimeout(action, timeout);
  }]));
  alias.apply(null, [Timer].concat(__slice.call('c,ct,cto,clear,clearTimeout'.split(',')), [function(handle) {
    return clearTimeout(handle);
  }]));
  alias.apply(null, [Timer].concat(__slice.call('i,in,iv,interval,setInterval'.split(',')), [function(timeout, action) {
    var _ref;
    _ref = validate(timeout, action), timeout = _ref[0], action = _ref[1];
    return setInterval(action, timeout);
  }]));
  timer = new Timer();
  Timer.prototype.Timer = Timer;
  return timer;
})();
